version: '3.8'

services:

  backend:
    image: vcarstein/electronicstore-backend:latest
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/mydatabase
      SPRING_DATASOURCE_USERNAME: userok
      SPRING_DATASOURCE_PASSWORD: p@ssword
    depends_on:
      - db
      - frontend

  frontend:
    image: vcarstein/electronicstore-frontend:latest
    ports:
      - "3000:8081"

  db:
    image: postgres:latest
    container_name: postgres_db
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: mydatabase
      POSTGRES_USER: userok
      POSTGRES_PASSWORD: p@ssword
    volumes:
      - postgres_data:/var/lib/postgresql/data